{{- if not .Values.useExternalSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ranger-tokens
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ranger.labels" . | nindent 4 }}
data:
  token: {{ default "" .Values.ranger.token | b64enc }}
  {{- with .Values.ranger.cfg.crawl.database }}
  {{- if and .name .connectionstring }}
  connectionstring-{{ .name }}: {{ .connectionstring | b64enc }}
  {{- end }}
  {{- end }}
type: Opaque
{{- end }}
